name: "Build & Test"

inputs:
  dotnet-version:
    description: "The .NET version to use."
    required: true
    default: "7.0.x"

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
      
    - name: Restore
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build -c Release
      shell: bash

    - name: Test
      run: dotnet test -c Release --collect:"XPlat Code Coverage" --test-adapter-path:. --logger "trx;LogFileName=test-results.trx"
      shell: bash

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Test Report
        path: "**/test-results.trx"
        reporter: dotnet-trx
      
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "**/coverage.cobertura.xml"
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
